from tkinter import *
root = Tk()
root.title('Login')
root.geometry('400x300')
frame= Frame(master =root, height=200, width=400, bg="#ffffff")
lbl1 = Label(frame, text = "Full name", bg= "#3895d3", fg='gray',width=12 )
lbl2 = Label(frame, text = "Email", bg= "#3895d3", fg='gray', width=12 )
lbl3 = Label(frame, text = "Password", bg= "#3895d3", fg='gray', width=12 )
name_entry= Entry(frame)
email_entry= Entry(frame)
pass_entry= Entry(frame, show="*")
def display():
    name = name_entry.get()
    greet = "Hello "+name+"!"
    message = "\nWelcome to the Application! for new accounts!  "
    textbox.insert(END, greet)
    textbox.insert(END, message)
textbox = Text(bg="#BEBEBE", fg= "black")
btn = Button(textbox, text="create account", command=display, bg = "red")
frame.place(x=20, y=0)
lbl1.place(x=20, y=20)
name_entry.place(x=150, y=20)
lbl2.place(x=20, y=80)
email_entry.place(x=150, y=80)
lbl3.place(x=20, y=140)
pass_entry.place(x=150, y=140)
btn.place(x=150, y=210)
textbox.place( y=250)
root.mainloop()